class DummyUser
  def self.data
    [
      { name: '山田太郎', id: 1, email: 'yamada.taro@example.com' },
      { name: '鈴木花子', id: 2, email: 'suzuki.hanako@example.com' },
      { name: '佐藤一郎', id: 3, email: 'sato.ichiro@example.com' },
      { name: '高橋美咲', id: 4, email: 'takahashi.misaki@example.com' },
      { name: '伊藤健太', id: 5, email: 'ito.kenta@example.com' },
      { name: '木村さくら', id: 6, email: 'kimura.sakura@example.com' },
      { name: '加藤翔', id: 7, email: 'kato.sho@example.com' },
      { name: '山口優衣', id: 8, email: 'yamaguchi.yui@example.com' },
      { name: '中村大輔', id: 9, email: 'nakamura.daisuke@example.com' },
      { name: '小林里奈', id: 10, email: 'kobayashi.rina@example.com' },
      { name: '渡辺太一', id: 11, email: 'watanabe.taichi@example.com' },
      { name: '田中陽菜', id: 12, email: 'tanaka.hina@example.com' },
      { name: '松本健', id: 13, email: 'matsumoto.ken@example.com' },
      { name: '井上さくら', id: 14, email: 'inoue.sakura@example.com' },
      { name: '山崎大樹', id: 15, email: 'yamazaki.hiroki@example.com' },
      { name: '吉田優里', id: 16, email: 'yoshida.yuri@example.com' },
      { name: '斎藤翔太', id: 17, email: 'saito.shota@example.com' },
      { name: '森ひなた', id: 18, email: 'mori.hinata@example.com' },
      { name: '池田健太郎', id: 19, email: 'ikeda.kentaro@example.com' },
      { name: '川口美優', id: 20, email: 'kawaguchi.miyu@example.com' },
      { name: '山本太一', id: 21, email: 'yamamoto.taichi@example.com' },
      { name: '中山さくら', id: 22, email: 'nakayama.sakura@example.com' },
      { name: '小川翔', id: 23, email: 'ogawa.sho@example.com' },
      { name: '高木陽菜', id: 24, email: 'takagi.hina@example.com' },
      { name: '西村大輔', id: 25, email: 'nishimura.daisuke@example.com' },
      { name: '井上里奈', id: 26, email: 'inoue.rina@example.com' },
      { name: '石川健', id: 27, email: 'ishikawa.ken@example.com' },
      { name: '前田優里', id: 28, email: 'maeda.yuri@example.com' },
      { name: '岡本翔太', id: 29, email: 'okamoto.shota@example.com' },
      { name: '山口ひなた', id: 30, email: 'yamaguchi.hinata@example.com' },
      { name: '中村健太郎', id: 31, email: 'nakamura.kentaro@example.com' },
      { name: '木村美優', id: 32, email: 'kimura.miyu@example.com' },
      { name: '田中太一', id: 33, email: 'tanaka.taichi@example.com' },
      { name: '小林さくら', id: 34, email: 'kobayashi.sakura@example.com' },
      { name: '渡辺翔', id: 35, email: 'watanabe.sho@example.com' },
      { name: '松本陽菜', id: 36, email: 'matsumoto.hina@example.com' },
      { name: '井上大輔', id: 37, email: 'inoue.daisuke@example.com' },
      { name: '山崎里奈', id: 38, email: 'yamazaki.rina@example.com' },
      { name: '吉田健', id: 39, email: 'yoshida.ken@example.com' },
      { name: '斎藤優里', id: 40, email: 'saito.yuri@example.com' },
      { name: '森翔太', id: 41, email: 'mori.shota@example.com' },
      { name: '池田ひなた', id: 42, email: 'ikeda.hinata@example.com' },
      { name: '川口健太郎', id: 43, email: 'kawaguchi.kentaro@example.com' },
      { name: '山本美優', id: 44, email: 'yamamoto.miyu@example.com' },
      { name: '中山太一', id: 45, email: 'nakayama.taichi@example.com' },
      { name: '小川さくら', id: 46, email: 'ogawa.sakura@example.com' },
      { name: '高木翔', id: 47, email: 'takagi.sho@example.com' },
      { name: '西村陽菜', id: 48, email: 'nishimura.hina@example.com' },
      { name: '石川大輔', id: 49, email: 'ishikawa.daisuke@example.com' },
      { name: '前田里奈', id: 50, email: 'maeda.rina@example.com' },
      { name: '岡本健', id: 51, email: 'okamoto.ken@example.com' },
      { name: '山口優里', id: 52, email: 'yamaguchi.yuri@example.com' },
      { name: '中村翔太', id: 53, email: 'nakamura.shota@example.com' },
      { name: '木村ひなた', id: 54, email: 'kimura.hinata@example.com' },
      { name: '田中健太郎', id: 55, email: 'tanaka.kentaro@example.com' },
      { name: '小林美優', id: 56, email: 'kobayashi.miyu@example.com' },
      { name: '渡辺太一', id: 57, email: 'watanabe.taichi@example.com' },
      { name: '松本さくら', id: 58, email: 'matsumoto.sakura@example.com' },
      { name: '井上翔', id: 59, email: 'inoue.sho@example.com' },
      { name: '山崎陽菜', id: 60, email: 'yamazaki.hina@example.com' }
    ]
  end
 
  def self.all
    data.map { |user| OpenStruct.new(user) }
  end
 end
 