class DummyUser
  def self.data
    [
      { name: 'John Smith', id: 1, email: 'john.smith@example.com' },
      { name: 'Emma Johnson', id: 2, email: 'emma.johnson@example.com' },
      { name: 'Michael Brown', id: 3, email: 'michael.brown@example.com' },
      { name: 'Olivia Davis', id: 4, email: 'olivia.davis@example.com' },
      { name: 'William Miller', id: 5, email: 'william.miller@example.com' },
      { name: 'Sophia Wilson', id: 6, email: 'sophia.wilson@example.com' },
      { name: 'Daniel Moore', id: 7, email: 'daniel.moore@example.com' },
      { name: 'Ava Taylor', id: 8, email: 'ava.taylor@example.com' },
      { name: 'Matthew Anderson', id: 9, email: 'matthew.anderson@example.com' },
      { name: 'Isabella Thomas', id: 10, email: 'isabella.thomas@example.com' },
      { name: 'Joshua Jackson', id: 11, email: 'joshua.jackson@example.com' },
      { name: 'Mia White', id: 12, email: 'mia.white@example.com' },
      { name: 'Andrew Harris', id: 13, email: 'andrew.harris@example.com' },
      { name: 'Abigail Martin', id: 14, email: 'abigail.martin@example.com' },
      { name: 'Joseph Thompson', id: 15, email: 'joseph.thompson@example.com' },
      { name: 'Emily Garcia', id: 16, email: 'emily.garcia@example.com' },
      { name: 'Christopher Martinez', id: 17, email: 'christopher.martinez@example.com' },
      { name: 'Harper Robinson', id: 18, email: 'harper.robinson@example.com' },
      { name: 'David Clark', id: 19, email: 'david.clark@example.com' },
      { name: 'Avery Rodriguez', id: 20, email: 'avery.rodriguez@example.com' },
      { name: 'William Lewis', id: 21, email: 'william.lewis@example.com' },
      { name: 'Amelia Walker', id: 22, email: 'amelia.walker@example.com' },
      { name: 'James Hall', id: 23, email: 'james.hall@example.com' },
      { name: 'Evelyn Allen', id: 24, email: 'evelyn.allen@example.com' },
      { name: 'Benjamin Young', id: 25, email: 'benjamin.young@example.com' },
      { name: 'Abigail King', id: 26, email: 'abigail.king@example.com' },
      { name: 'Michael Wright', id: 27, email: 'michael.wright@example.com' },
      { name: 'Emily Scott', id: 28, email: 'emily.scott@example.com' },
      { name: 'Daniel Green', id: 29, email: 'daniel.green@example.com' },
      { name: 'Olivia Baker', id: 30, email: 'olivia.baker@example.com' },
      { name: 'Jacob Parker', id: 31, email: 'jacob.parker@example.com' },
      { name: 'Sophia Rivera', id: 32, email: 'sophia.rivera@example.com' },
      { name: 'Ethan Cooper', id: 33, email: 'ethan.cooper@example.com' },
      { name: 'Isabella Peterson', id: 34, email: 'isabella.peterson@example.com' },
      { name: 'Michael Bailey', id: 35, email: 'michael.bailey@example.com' },
      { name: 'Emma Murphy', id: 36, email: 'emma.murphy@example.com' },
      { name: 'William Phillips', id: 37, email: 'william.phillips@example.com' },
      { name: 'Ava Campbell', id: 38, email: 'ava.campbell@example.com' },
      { name: 'Daniel Barnes', id: 39, email: 'daniel.barnes@example.com' },
      { name: 'Abigail Stewart', id: 40, email: 'abigail.stewart@example.com' },
      { name: 'Joseph Sanchez', id: 41, email: 'joseph.sanchez@example.com' },
      { name: 'Mia Rogers', id: 42, email: 'mia.rogers@example.com' },
      { name: 'Henry Ramirez', id: 43, email: 'henry.ramirez@example.com' },
      { name: 'Emily Watson', id: 44, email: 'emily.watson@example.com' },
      { name: 'Alexander Henderson', id: 45, email: 'alexander.henderson@example.com' },
      { name: 'Avery Sanders', id: 46, email: 'avery.sanders@example.com' },
      { name: 'Joshua Long', id: 47, email: 'joshua.long@example.com' },
      { name: 'Amelia Patterson', id: 48, email: 'amelia.patterson@example.com' },
      { name: 'Christopher Gray', id: 49, email: 'christopher.gray@example.com' },
      { name: 'Harper Cox', id: 50, email: 'harper.cox@example.com' },
      { name: 'Andrew Simmons', id: 51, email: 'andrew.simmons@example.com' },
      { name: 'Abigail Foster', id: 52, email: 'abigail.foster@example.com' },
      { name: 'Joseph Burton', id: 53, email: 'joseph.burton@example.com' },
      { name: 'Emily Chapman', id: 54, email: 'emily.chapman@example.com' },
      { name: 'Matthew Torres', id: 55, email: 'matthew.torres@example.com' },
      { name: 'Avery Hunter', id: 56, email: 'avery.hunter@example.com' },
      { name: 'Daniel Hudson', id: 57, email: 'daniel.hudson@example.com' },
      { name: 'Sophia Freeman', id: 58, email: 'sophia.freeman@example.com' },
      { name: 'Benjamin Owens', id: 59, email: 'benjamin.owens@example.com' },
      { name: 'Isabella Shaw', id: 60, email: 'isabella.shaw@example.com' }
    ]
  end

  def self.all
    data.map { |user| OpenStruct.new(user) }
  end
end
